# Generated by Django 3.2.4 on 2021-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webo_app', '0003_auto_20210710_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaperdetail',
            name='doi',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
