# Generated by Django 3.2.4 on 2021-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webo_app', '0004_alter_researchpaperdetail_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaperdetail',
            name='doi',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
